name: unittest
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
jobs:
  karma-chrome:
    name: Karma unit test (Chrome)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn install
      - name: Run the test suite
        run: yarn gulp test:unit
  karma-firefox:
    name: Karma unit test (Firefox)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn install
      - name: Run the test suite
        run: yarn gulp test:unit -b Firefox
